---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "generic-app.fullname" . }}-env-cm
  labels:
    {{- include "generic-app.labels" . | nindent 4 }}
data: {{- .Values.config | toYaml | nindent 2 }}
{{- range .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  labels:
    {{- include "generic-app.labels" $ | nindent 4 }}
data: {{- .data | toYaml | nindent 2 }}
{{- end }}
