{{- if .Values.HTTPRoute.enabled -}}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "generic-app.fullname" . }}
  labels:
    {{- include "generic-app.labels" . | nindent 4 }}
  {{- with .Values.HTTPRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
  {{- range .Values.HTTPRoute.parentRefs }}
  - group: {{ .group }}
    kind: {{ .kind }}
    name: {{ .name }}
    namespace: {{ .namespace | default "istio-system" }}
  {{- end }}
  hostnames:
  {{- range .Values.HTTPRoute.hostnames }}
  - {{ . | quote }}
  {{- end }}
  rules:
  {{- range .Values.HTTPRoute.rules }}
  - {{- if .matches }}
    matches: {{- .matches | toYaml | nindent 4 }}
    {{- end }}
    {{- if .filters }}
    filters: {{- .filters | toYaml | nindent 4 }}
    {{- end }}
    backendRefs:
    {{- range .backendRefs }}
    - group: ""
      kind: {{ .kind | default "Service" }}
      name: {{ include "generic-app.fullname" $ }}
      port: {{ .port }}
      weight: {{ .weight | default 1 }}
    {{- end }}
  {{- end }}
{{- end }}
