{{- if .Values.statefulSet.enabled }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "generic-app.fullname" . }}
  labels:
    {{- include "generic-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "generic-app.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "generic-app.fullname" . }}
  template:
    metadata:
      annotations:
        {{- if .Values.statefulSet.restartOnChanges }}
        values-hash: {{ include "values.hash" . | quote }}
        {{- end }}
        configmap-hash: {{ include "configmap.hash" . }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "generic-app.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "generic-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{- range $container := .Values.initContainers }}
        - securityContext:
            {{- toYaml $.Values.initContainerSecurityContext | nindent 12 }}
          {{- with $container }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- end }}
      containers:
        {{- with .Values.extraContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: {{ .Release.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.workingDir }}
          workingDir: {{ . }}
          {{- end }}
          {{- with .Values.command }}
          command: {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.args }}
          args: {{- . | toYaml | nindent 12 }}
          {{- end }}
          ports:
          {{- if .Values.service.ports }}
          {{- range $idx, $port := .Values.service.ports }}
            - name: {{ $port.name }}
              containerPort: {{ $port.port }}
              protocol: {{ $port.protocol }}
          {{- end }}
          {{- else }}
            []
          {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "generic-app.fullname" . }}-env-cm
            {{- with .Values.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          env: {{- toYaml .Values.env | nindent 12 }}
          {{- if or .Values.volumeMounts .Values.statefulSet.persistence.enabled }}
          volumeMounts:
          {{- if .Values.statefulSet.persistence.enabled }}
            - name: data
              mountPath: {{ .Values.statefulSet.persistence.mountPath }}
          {{- end }}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- with .Values.runtimeClassName }}
      runtimeClassName: {{ . | quote }}
      {{- end }}
  {{- if .Values.statefulSet.persistence.enabled }}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
        labels:
          {{- include "generic-app.labels" . | nindent 10 }}
      spec:
        storageClassName: {{ .Values.statefulSet.persistence.storageClassName | quote }}
        accessModes: {{- .Values.statefulSet.persistence.accessModes | toYaml | nindent 10 }}
        resources:
          requests:
            storage: {{ .Values.statefulSet.persistence.size }}
    {{- end }}
{{- end }}
