nameOverride: "generic-deployment"

image:
  repository: alpine
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"
imagePullSecrets: []

replicaCount: 1
deployment:
  enabled: true
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1

command: []
args: []

# -- config is the most straightforward way to set environment variables for your application, the key/value configmap will be mounted as envs. No need to do any extra configuration.
config: {}
  # ENV_1: value1
  # ENV_2: value2

service:
  ports:
    - name: http
      port: 8080
      protocol: TCP

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
          # -- Port name as defined in the service.ports section
          portName: http
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

serviceMonitor:
  enabled: false

terminationGracePeriodSeconds: 30

dnsConfig: {}
# Example:
# dnsConfig:
  # nameservers:
  #   - "8.8.8.8"
  # searches:
  #   - "gardia.zenrocklabs.io"
  # options:
  #   - name: "ndots"
  #     value: "2"
  #   - name: "timeout"
  #     value: "2"
  #   - name: "attempts"
  #     value: "5"
